pipeline {
    agent {
        docker {
            image 'node:latest'
            args '-p 5000:5000'
        }
    }
    environment {
        PORT=5000
    } 
    stages {
        stage('Install') {
            steps {
                sh 'npm install'
            }
        }
        stage('Linter') {
            steps {
                sh 'npm run linter'
            }
        }
        stage('Test') {
            steps {
                script {
                    try{
                        sh 'npm test'
                    }catch(Exception e){
                        def skipTestFailure = input(message: 'Test in failure, proceed ?', 
                            parameters: [booleanParam(defaultValue: true, 
                            description: 'proceed', name: 'yes ?')])
                        if(skipTestFailure){
                            currentBuild.result = 'UNSTABLE'
                        } else{
                            currentBuild.result = 'FAILURE'
                            error('Test in failure')
                        }
                    }
                }
            }
        }
        stage('Build') {
            steps {
                sh 'npm run build-prod'
            }
        }
        stage('Compile') {
            steps {
                sh 'npm run compile-prod'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
        stage('Clean') {
            steps {
                sh './jenkins/scripts/clean.sh'
            }
        }
    }
}